### ISSUE TITLE
recommend an AutoML survey

### ISSUE THREAD

**Issue by marsggbo** [windmaple/awesome-AutoML#8]
https://arxiv.org/abs/1908.00709

@article{he2019automl,
  title={AutoML: A Survey of the State-of-the-Art},
  author={He, Xin and Zhao, Kaiyong and Chu, Xiaowen},
  journal={arXiv preprint arXiv:1908.00709},
  year={2019}
}

**Comment by windmaple** [comment]
Added. Thanks for the suggestion!
